spring.application.name=HospitalManagementSystem1
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDb
spring.datasource.username= postgres
spring.datasource.password=Mrinmoy@23

server.servlet.context.path=/api/v1

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true 
# spring.jpa.properties.hibernate.format_sql= false



# 2. Force the SQL scripts to run AFTER Hibernate is done
spring.jpa.defer-datasource-initialization=true

# 3. Ensure the initialization mode is active
spring.sql.init.mode=always

# 4. Point to your data file
spring.sql.init.data-locations=classpath:data.sql



